// <auto-generated />
using AlzaProduct.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlzaProduct.Infrastructure.Migrations
{
    [DbContext(typeof(AlzaDbContext))]
    [Migration("20241108063724_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlzaProduct.Domain.Entities.Products.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "08de68db-5596-49ea-b5cf-70489f4ffdb8",
                            Description = "Description 1",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 1",
                            Price = 129.59m
                        },
                        new
                        {
                            Id = "db84e74c-a5fa-4390-9a4f-0e4e71633c8d",
                            Description = "Description 2",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 2",
                            Price = 345.81m
                        },
                        new
                        {
                            Id = "17469621-4a74-4c3b-8ccb-662c0cac87e8",
                            Description = "Description 3",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 3",
                            Price = 363.80m
                        },
                        new
                        {
                            Id = "4e4fdd5c-3dae-48a5-ba98-b4455120346d",
                            Description = "Description 4",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 4",
                            Price = 113.40m
                        },
                        new
                        {
                            Id = "51c9da66-0892-4683-ba8d-951daea7166a",
                            Description = "Description 5",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 5",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = "5b223af9-c031-4ee7-8ad0-3d04a7624cdb",
                            Description = "Description 6",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 6",
                            Price = 612.20m
                        },
                        new
                        {
                            Id = "87b25e8f-3cbf-4a31-a805-a1aa031dea75",
                            Description = "Description 7",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 7",
                            Price = 636.05m
                        },
                        new
                        {
                            Id = "2ec1bf5c-d11a-4fd4-9073-9c280f6a20bd",
                            Description = "Description 8",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 8",
                            Price = 475.95m
                        },
                        new
                        {
                            Id = "e9932a4b-c1d3-4734-a401-65759d4289a9",
                            Description = "Description 9",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 9",
                            Price = 216.82m
                        },
                        new
                        {
                            Id = "19a8e425-d37b-434e-804e-27eafa5fbaeb",
                            Description = "Description 10",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 10",
                            Price = 336.29m
                        },
                        new
                        {
                            Id = "91534f77-cc29-49d6-a8ae-dcc0d750cc44",
                            Description = "Description 11",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 11",
                            Price = 347.68m
                        },
                        new
                        {
                            Id = "e80afaae-55f1-4afc-93b4-6c022d9eab41",
                            Description = "Description 12",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 12",
                            Price = 597.52m
                        },
                        new
                        {
                            Id = "f43e33d7-a7b9-494e-ad87-8f925820d9ab",
                            Description = "Description 13",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 13",
                            Price = 981.08m
                        },
                        new
                        {
                            Id = "77a328ed-ea45-4942-9427-4af5c33690c7",
                            Description = "Description 14",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 14",
                            Price = 907.78m
                        },
                        new
                        {
                            Id = "a38a2fa5-d40c-4334-b343-d31b8ba4855e",
                            Description = "Description 15",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 15",
                            Price = 202.92m
                        },
                        new
                        {
                            Id = "77fc32b3-2e9c-4295-b49d-df7fafd9e1da",
                            Description = "Description 16",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 16",
                            Price = 461.67m
                        },
                        new
                        {
                            Id = "4a21f55f-8183-4847-b99f-f254f4bb7d59",
                            Description = "Description 17",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 17",
                            Price = 302.10m
                        },
                        new
                        {
                            Id = "4a9bb231-f772-4010-b682-eb08edcb7db2",
                            Description = "Description 18",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 18",
                            Price = 513.67m
                        },
                        new
                        {
                            Id = "3acd5902-ff03-4264-a065-b8f47b520a34",
                            Description = "Description 19",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 19",
                            Price = 848.56m
                        },
                        new
                        {
                            Id = "e224d429-689d-446c-ba89-857448f87db0",
                            Description = "Description 20",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 20",
                            Price = 868.10m
                        },
                        new
                        {
                            Id = "ffb56498-846b-43f5-954d-cdbbc546f4dd",
                            Description = "Description 21",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 21",
                            Price = 136.91m
                        },
                        new
                        {
                            Id = "19daa9ed-0d56-4e2d-a718-4d3bf8491444",
                            Description = "Description 22",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 22",
                            Price = 238.89m
                        },
                        new
                        {
                            Id = "d9564451-c9d3-4cf3-8a16-275a4024bba9",
                            Description = "Description 23",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 23",
                            Price = 756.66m
                        },
                        new
                        {
                            Id = "98df81db-a485-4ba6-8816-571a4d085705",
                            Description = "Description 24",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 24",
                            Price = 115.46m
                        },
                        new
                        {
                            Id = "bf4faf3d-ed5f-4d75-8e10-e3bdf752bb6c",
                            Description = "Description 25",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 25",
                            Price = 881.72m
                        },
                        new
                        {
                            Id = "767d60f8-b344-455b-9011-d36eeda7d6e2",
                            Description = "Description 26",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 26",
                            Price = 372.20m
                        },
                        new
                        {
                            Id = "e5487736-bb13-42ba-9905-542280637bbf",
                            Description = "Description 27",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 27",
                            Price = 178.41m
                        },
                        new
                        {
                            Id = "2d8a9129-60ce-4f4d-ab30-91ad51aa2f41",
                            Description = "Description 28",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 28",
                            Price = 245.39m
                        },
                        new
                        {
                            Id = "df189d0b-9416-4eee-8673-a4fff2498f2d",
                            Description = "Description 29",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 29",
                            Price = 871.61m
                        },
                        new
                        {
                            Id = "aa80333c-934d-485e-903e-2a9dc1c943c3",
                            Description = "Description 30",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 30",
                            Price = 744.94m
                        },
                        new
                        {
                            Id = "af448915-dfe6-44ff-8ec0-eb99e36ea99c",
                            Description = "Description 31",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 31",
                            Price = 171.46m
                        },
                        new
                        {
                            Id = "97270f45-6245-47d6-b2ef-0006eb7cadb3",
                            Description = "Description 32",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 32",
                            Price = 210.94m
                        },
                        new
                        {
                            Id = "9afa0506-a7b7-47a6-9728-f7cc07bbcd2f",
                            Description = "Description 33",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 33",
                            Price = 110.00m
                        },
                        new
                        {
                            Id = "e87fc434-a426-49e2-8b19-e1cd0aa484dc",
                            Description = "Description 34",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 34",
                            Price = 649.93m
                        },
                        new
                        {
                            Id = "c930188a-acb2-4f09-8f11-de4be1079e5c",
                            Description = "Description 35",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 35",
                            Price = 856.37m
                        },
                        new
                        {
                            Id = "f12d77c8-0777-4d0b-bfcc-c9c79d4a1c90",
                            Description = "Description 36",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 36",
                            Price = 141.72m
                        },
                        new
                        {
                            Id = "586f5266-b304-40dc-94b0-c0ad2350be97",
                            Description = "Description 37",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 37",
                            Price = 243.74m
                        },
                        new
                        {
                            Id = "0a55445d-2f8f-4173-bf30-8b2239fa1529",
                            Description = "Description 38",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 38",
                            Price = 656.32m
                        },
                        new
                        {
                            Id = "483cd807-e136-43f7-9285-d199591d05ea",
                            Description = "Description 39",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 39",
                            Price = 505.28m
                        },
                        new
                        {
                            Id = "f0b56a97-4d9d-4376-bca3-00a61dcee4e7",
                            Description = "Description 40",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 40",
                            Price = 223.34m
                        },
                        new
                        {
                            Id = "9770ba20-4bd2-4248-9b0a-c0eb214d3c92",
                            Description = "Description 41",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 41",
                            Price = 830.81m
                        },
                        new
                        {
                            Id = "abd1c427-68fa-463f-a71a-dd2d528d031d",
                            Description = "Description 42",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 42",
                            Price = 855.21m
                        },
                        new
                        {
                            Id = "3d351912-c96b-4156-b4e3-118746530eb4",
                            Description = "Description 43",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 43",
                            Price = 637.23m
                        },
                        new
                        {
                            Id = "84a0259b-7433-472a-8b3f-97a811cc9f8b",
                            Description = "Description 44",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 44",
                            Price = 929.58m
                        },
                        new
                        {
                            Id = "5c63c4ae-15fc-49d6-ab9c-b551cf1773fb",
                            Description = "Description 45",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 45",
                            Price = 191.21m
                        },
                        new
                        {
                            Id = "b99044fa-55fb-4195-a551-329b47a024cb",
                            Description = "Description 46",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 46",
                            Price = 275.82m
                        },
                        new
                        {
                            Id = "cfffca43-3c9a-42f6-a1a5-804977ea51e2",
                            Description = "Description 47",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 47",
                            Price = 780.48m
                        },
                        new
                        {
                            Id = "a2a55d0f-8227-4dc8-a054-75a452e9e67e",
                            Description = "Description 48",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 48",
                            Price = 453.36m
                        },
                        new
                        {
                            Id = "26be1feb-e4ab-4cf6-85f4-48471c66926b",
                            Description = "Description 49",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 49",
                            Price = 753.75m
                        },
                        new
                        {
                            Id = "ad7d6f36-e5d5-4c22-92b0-f1449ea4efe1",
                            Description = "Description 50",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 50",
                            Price = 425.01m
                        },
                        new
                        {
                            Id = "4b1015d8-9177-4e2b-8f85-e9b91403350d",
                            Description = "Description 51",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 51",
                            Price = 564.88m
                        },
                        new
                        {
                            Id = "3be33575-bd9b-4b12-adfd-40c45deb5095",
                            Description = "Description 52",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 52",
                            Price = 393.30m
                        },
                        new
                        {
                            Id = "969b2c8c-b3f1-4617-b24e-e1579e53d5f1",
                            Description = "Description 53",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 53",
                            Price = 868.35m
                        },
                        new
                        {
                            Id = "802b533b-b113-44d3-8626-aa8e47bd059e",
                            Description = "Description 54",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 54",
                            Price = 960.18m
                        },
                        new
                        {
                            Id = "2f331b91-8564-44a4-9786-8123620415dc",
                            Description = "Description 55",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 55",
                            Price = 421.20m
                        },
                        new
                        {
                            Id = "ccbf609d-b8d5-454f-a3e9-7fe7158f3f5a",
                            Description = "Description 56",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 56",
                            Price = 291.57m
                        },
                        new
                        {
                            Id = "4196950e-5ff8-45ce-81f9-d343cfb1c55d",
                            Description = "Description 57",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 57",
                            Price = 739.97m
                        },
                        new
                        {
                            Id = "d2760762-4630-4459-ab06-1b122791e6ad",
                            Description = "Description 58",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 58",
                            Price = 426.62m
                        },
                        new
                        {
                            Id = "0081d8f6-c794-4cd6-b5d5-146eddfe2fa1",
                            Description = "Description 59",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 59",
                            Price = 775.66m
                        },
                        new
                        {
                            Id = "205f0044-73c7-44dd-8c7e-44423149b9fd",
                            Description = "Description 60",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 60",
                            Price = 677.13m
                        },
                        new
                        {
                            Id = "942792b2-ca4e-4768-a978-409e45f156d1",
                            Description = "Description 61",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 61",
                            Price = 969.91m
                        },
                        new
                        {
                            Id = "526195e8-de6e-4aa7-9bee-211d225c1e49",
                            Description = "Description 62",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 62",
                            Price = 877.65m
                        },
                        new
                        {
                            Id = "22606302-aeaa-4339-8397-8c2a176bbf63",
                            Description = "Description 63",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 63",
                            Price = 816.87m
                        },
                        new
                        {
                            Id = "0b3880bb-9a91-40bc-8ef0-6dc897126e70",
                            Description = "Description 64",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 64",
                            Price = 244.31m
                        },
                        new
                        {
                            Id = "21a9bbc6-8215-42e2-864a-f9c635dc6907",
                            Description = "Description 65",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 65",
                            Price = 811.07m
                        },
                        new
                        {
                            Id = "993120dd-3662-46f3-a983-9f4a1df98807",
                            Description = "Description 66",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 66",
                            Price = 643.78m
                        },
                        new
                        {
                            Id = "cfbe6b4e-2744-4f61-8e9d-feaa4459734c",
                            Description = "Description 67",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 67",
                            Price = 439.77m
                        },
                        new
                        {
                            Id = "6fc20ff2-1fe9-457f-b1e8-0a4074b3bd1d",
                            Description = "Description 68",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 68",
                            Price = 405.24m
                        },
                        new
                        {
                            Id = "dd397ddd-7fd6-4898-93b5-fdf630d02a80",
                            Description = "Description 69",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 69",
                            Price = 912.96m
                        },
                        new
                        {
                            Id = "37dd476b-9f66-40b0-b74b-061c75de8453",
                            Description = "Description 70",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 70",
                            Price = 846.51m
                        },
                        new
                        {
                            Id = "66a50667-33aa-4014-b427-48a0c5b6eeec",
                            Description = "Description 71",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 71",
                            Price = 370.54m
                        },
                        new
                        {
                            Id = "b2a0ba16-59f9-480a-b21f-350a1a9a71d6",
                            Description = "Description 72",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 72",
                            Price = 697.57m
                        },
                        new
                        {
                            Id = "4db44798-0143-4a5e-8ce9-50218bfae1ee",
                            Description = "Description 73",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 73",
                            Price = 712.76m
                        },
                        new
                        {
                            Id = "d67c5e30-cbdc-423e-824c-e61b4df631e1",
                            Description = "Description 74",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 74",
                            Price = 309.64m
                        },
                        new
                        {
                            Id = "edebae29-2650-4d1e-a2ae-4bc607e01509",
                            Description = "Description 75",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 75",
                            Price = 414.94m
                        },
                        new
                        {
                            Id = "cc938155-9463-4beb-9ba0-c2d2b9392827",
                            Description = "Description 76",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 76",
                            Price = 221.31m
                        },
                        new
                        {
                            Id = "66251bb4-0d58-4d6c-9cc4-5db609904616",
                            Description = "Description 77",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 77",
                            Price = 479.08m
                        },
                        new
                        {
                            Id = "5d6a0a14-83bf-4cba-ae8e-67c0502b4f69",
                            Description = "Description 78",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 78",
                            Price = 549.59m
                        },
                        new
                        {
                            Id = "28d47b67-ddca-4c2f-a11c-74c0ec8f31b0",
                            Description = "Description 79",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 79",
                            Price = 958.50m
                        },
                        new
                        {
                            Id = "666c3594-112b-45f4-a53b-5028533452e6",
                            Description = "Description 80",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 80",
                            Price = 131.57m
                        },
                        new
                        {
                            Id = "449798b6-6045-44a6-a417-0ea129487eeb",
                            Description = "Description 81",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 81",
                            Price = 297.43m
                        },
                        new
                        {
                            Id = "6d6d74b7-8eae-4ad8-bd24-d3640450734f",
                            Description = "Description 82",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 82",
                            Price = 262.10m
                        },
                        new
                        {
                            Id = "989c28d5-df87-4e49-80a5-83ce75ab2ce5",
                            Description = "Description 83",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 83",
                            Price = 574.42m
                        },
                        new
                        {
                            Id = "b824f56c-49c6-4c26-bfb4-2092c50225e2",
                            Description = "Description 84",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 84",
                            Price = 726.21m
                        },
                        new
                        {
                            Id = "96ef1478-e86f-49da-89ce-1037795ad5fd",
                            Description = "Description 85",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 85",
                            Price = 519.58m
                        },
                        new
                        {
                            Id = "76552437-df18-4fa6-824a-679c2f24c73a",
                            Description = "Description 86",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 86",
                            Price = 365.37m
                        },
                        new
                        {
                            Id = "04f331fc-2f88-4c20-a9a4-3bfae1421557",
                            Description = "Description 87",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 87",
                            Price = 671.95m
                        },
                        new
                        {
                            Id = "55a91ef7-1985-4c96-8d8e-a5b26956ff4a",
                            Description = "Description 88",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 88",
                            Price = 758.88m
                        },
                        new
                        {
                            Id = "abb85792-9429-4d7b-a677-68cea45ab51d",
                            Description = "Description 89",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 89",
                            Price = 783.94m
                        },
                        new
                        {
                            Id = "b3671c85-3577-4ddc-b709-3945b4c52881",
                            Description = "Description 90",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 90",
                            Price = 511.73m
                        },
                        new
                        {
                            Id = "93c8ebe5-fe3e-44e0-95ba-c3903c51307b",
                            Description = "Description 91",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 91",
                            Price = 776.22m
                        },
                        new
                        {
                            Id = "1728b057-7e69-4b99-8898-349d7db98932",
                            Description = "Description 92",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 92",
                            Price = 140.69m
                        },
                        new
                        {
                            Id = "b9a37e11-8141-460d-8408-3161da1553d7",
                            Description = "Description 93",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 93",
                            Price = 263.89m
                        },
                        new
                        {
                            Id = "228e2437-1a7d-4a08-829d-3d519cb89441",
                            Description = "Description 94",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 94",
                            Price = 820.07m
                        },
                        new
                        {
                            Id = "23752181-8071-4b2a-936a-e9479acbb139",
                            Description = "Description 95",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 95",
                            Price = 225.65m
                        },
                        new
                        {
                            Id = "45223532-5313-49ad-b991-6a54e30638ce",
                            Description = "Description 96",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 96",
                            Price = 278.92m
                        },
                        new
                        {
                            Id = "3eca1561-b9c8-4169-a4ad-5ca052e320ae",
                            Description = "Description 97",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 97",
                            Price = 887.56m
                        },
                        new
                        {
                            Id = "101349ef-0c5a-475b-a9a1-0c29967bf74f",
                            Description = "Description 98",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 98",
                            Price = 981.28m
                        },
                        new
                        {
                            Id = "c6c0e9fb-a7b1-4035-be3f-6531f706bc0a",
                            Description = "Description 99",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 99",
                            Price = 543.44m
                        },
                        new
                        {
                            Id = "ffef38b0-6de2-4e4a-9748-57458c00e672",
                            Description = "Description 100",
                            ImgUri = "https://via.placeholder.com/150",
                            Name = "Product 100",
                            Price = 975.77m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
